# Generated by Django 5.2 on 2025-05-12 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='picture',
            field=models.ImageField(blank=True, upload_to='pictures/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
