# Generated by Django 5.2.1 on 2025-05-21 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_categoria_proposta_avaliacao_servico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='nota',
            field=models.IntegerField(choices=[(1, '1 - Péssimo'), (2, '2 - Ruim'), (3, '3 - Regular'), (4, '4 - Bom'), (5, '5 - Excelente')]),
        ),
    ]
