# Generated by Django 5.2.1 on 2025-05-24 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_alter_avaliacao_nota'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='sobre',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
