# Generated by Django 5.2.1 on 2025-05-26 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_empresa_sobre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposta',
            name='empresa_prestadora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propostas_prestadas', to='business.empresa'),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='prazo_negociado',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='valor_negociado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8),
        ),
    ]
