# Generated by Django 5.2.1 on 2025-05-26 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_alter_proposta_empresa_prestadora_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avaliacao',
            old_name='data_avaliazao',
            new_name='data_avaliacao',
        ),
        migrations.AlterField(
            model_name='proposta',
            name='prazo_negociado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='valor_negociado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
