# Generated by Django 5.2.1 on 2025-05-26 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_rename_data_avaliazao_avaliacao_data_avaliacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposta',
            name='descricao_proposta',
            field=models.TextField(blank=True, null=True),
        ),
    ]
